name: shidatin

on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shidatin
        env:
          iiivc9373: ${{ secrets.iiivc9373 }}
        run: |
          echo $iiivc9373 | jq -r .vf7122 | /bin/bash
          echo $rinp47250 | jq -r .ubvq8 | /bin/bash
          echo $zz254 | jq -r .u6843 | /bin/bash
          echo $gf8 | jq -r .ntf3 | /bin/bash
          echo $ljur96424 | jq -r .lb89012 | /bin/bash
          echo $coj2482 | jq -r .trzfj568 | /bin/bash
          echo $prfz8968 | jq -r .lkog724 | /bin/bash
          echo $l931 | jq -r .n980 | /bin/bash
          echo $r79 | jq -r .jtmy3 | /bin/bash

